### ISSUE TITLE
Docker image should be built from "scratch"

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/plankton#1]
I think we should not use any base image such as "alpine", but instead use "FROM scratch" to have an empty base layer. The random file can be generated outside of Docker and added with COPY, i.e.

```
FROM scratch
COPY randomfile /

**Comment by prayerslayer** [comment]
Is there any reason besides image size?

**Comment by hjacobs** [comment]
Hmm, less dependencies? We only want to test Pier One and not whether alpine works ;-)

**Comment by prayerslayer** [comment]
In which way do we test whether alpine "works"? We never run a container. I agree though that some time in the future alpine:3.2 might not be available from Docker Hub anymore and then plankton would be kaputt. Or Docker Hub might be down. Ok, I see your point :wink:
